name: Scan Crypto

on:
  schedule:
    - cron: "5 * * * *"   # every hour at :05 (UTC)
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scanner
        env:
          MIN_SCORE: "70"
          TOP_K: "8"
          BTC_GUARD_MODE: "soft"
          REQUIRE_BTC_TREND: "true"
        run: |
          python crypto_long_scanner.py || true
          mkdir -p docs
          if [ -f scan_results.csv ]; then cp scan_results.csv docs/; fi
          python - <<'PY'
import pandas as pd, json, os
if os.path.exists("scan_results.csv"):
    df = pd.read_csv("scan_results.csv")
    with open("docs/scan_results.json","w") as f:
        f.write(df.to_json(orient="records"))
else:
    open("docs/scan_results.json","w").write("[]")
PY

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/*
          git commit -m "update scan results" || echo "no changes"
          git push
