name: Scan Crypto
on:
  schedule:
    - cron: "5 * * * *"   # every hour at :05 (UTC)
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run scanner
        env:
          MIN_SCORE: "70"
          TOP_K: "8"
          BTC_GUARD_MODE: "soft"
          REQUIRE_BTC_TREND: "true"
        run: |
          python crypto_long_scanner.py || true
          # copy JSON to docs for GitHub Pages
          mkdir -p docs
          if [ -f scan_results.csv ]; then cp scan_results.csv docs/; fi
          # Create JSON snapshot from CSV if needed
          python - <<'PY'
import pandas as pd, json
try:
    df = pd.read_csv("scan_results.csv")
    open("docs/scan_results.json","w").write(df.to_json(orient="records"))
except Exception as e:
    open("docs/scan_results.json","w").write("[]")
PY
      - name: Commit & push
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/*
          git commit -m "update scan results" || echo "no changes"
          git push
